apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9091"
spec:
  selector:
    app: prometheus-pushgateway
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091


